"""Initial migration

Revision ID: 8f6e717439da
Revises: 
Create Date: 2025-03-01 07:10:20.888629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f6e717439da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('vimeo_url', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('vimeo_id', sa.String(), nullable=True))
    op.drop_column('videos', 'video')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('video', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('videos', 'vimeo_id')
    op.drop_column('videos', 'vimeo_url')
    # ### end Alembic commands ###
